### ISSUE TITLE
beacon: simple query

### ISSUE THREAD

**Issue by trentmswanson** [ClinGen/clinbeacon#16]
Dependency on #15

**Comment by snehitp** [comment]
It was decided to implement a simple GA4GH beacon query as a starting point for this conversation:
Query: "Has any tenant seen a patient with variant X"? 
Response: Yes / No from each tenant.

X here can be some identifier for the variant (e.g. chromosome number, position). If there are multiple mutations at this position (e.g. A->C and A->G), then having a patient with any one may be counted as a match.

**Comment by trentmswanson** [comment]
In the example 'A' is the reference for the given build, correct? Where exactly in the VCF do I match 'G' or 'C'?  The snippet below is from that mongo import and pyVCF.

```
{'gt_nums': '0/1', 'ploidity': 2, 'sample': 'NIST7086', 'gt_bases': 'C/G', 'pos': 14699, 'gt_alleles': ['0', '1'], 'qual': 425.44, 'chrom': 'chr1', 'ref': 'C', '_id': ObjectId('57617e43e8de73010da3a5c9'), 'calldata': {'DP': 125, 'PL': [194, 0, 2368], 'GT': '0/1', 'GQ': 99, 'AD': [108, 17]}, 'phased': False}
```
