### ISSUE TITLE
beacon: security design

### ISSUE THREAD

**Issue by trentmswanson** [ClinGen/clinbeacon#17]

**Comment by trentmswanson** [comment]
The clingen hub will need to trust the beacon
The clingen hub will also need to be able to authenticate to the beacon

**Comment by slowkoni** [comment]
Both tenant and central server should authenticate to each other and not trust each other without it. Tenant authentication should probably be part of service discovery and a tenant not allowed to join if it fails to authenticate properly. Service discovery could rechallenge periodically. Both sides should probably have an SSL certificate, but we could issue the tenant SSL certs signed by us so the tenants don't have to buy CA signed certs. We just add our signing cert to the central server's trusted certs store. The central server ought to have a CA signed cert though. It will need one anyway for talking to querying clients.

**Comment by trentmswanson** [comment]
Agreed.  The trust would likely be established through the use of certificates.

**Comment by trentmswanson** [comment]
The design details have been worked out and we are currently implementing
