### ISSUE TITLE
documentation: genotype storage and query complexity

### ISSUE THREAD

**Issue by slowkoni** [ClinGen/clinbeacon#25]
Start a google doc with a discussion of the complexity expected for both the storage and query of genotypes. Snehit to start, Koni to add/refine. 

This task specifically refers to explanation and discussion of the problem until the entire group understands both the existence and nature of the problem as early in all this as possible. The ultimate solution to it may not be an MVP item.

**Comment by snehitp** [comment]
Done. See https://docs.google.com/document/d/173JlHMBVDVt0q2I8IVAen6hwF1cfTsycLvN3ZtYoJvs/edit
