### ISSUE TITLE
npm issue / setup and launch troubles for beacon client

### ISSUE THREAD

**Issue by slowkoni** [ClinGen/clinbeacon#66]
Trouble with installation of needed node/js modules with npm in setting up a launch of the beacon client. Seen by Koni and Karen on Docker on OS X. Symptom is a file & directory that can not be removed but npm won't continue unless it is. Unknown if this is a docker issue. Regardless, it should be possible to remove the file but it isn't. It seems like fs corruption and normally I would fsck, but one can't do that to a docker-provided fs, thus why I suspect OS X docker beta. Need to see if happens on Linux docker.

**Comment by slowkoni** [comment]
npm errors/warnings seen on OS X during a fresh exec of cd ./ui && npm install for beacon client 

npm WARN lifecycle clinbeacon@1.0.0~postinstall: cannot run in wd %s %s (wd=%s) clinbeacon@1.0.0 typings install /app/ui
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/core@2.0.0-rc.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/http@2.0.0-rc.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/router@3.0.0-beta.2 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.14 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN angular2-jwt@0.1.18 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN clinbeacon@1.0.0 No description
npm WARN clinbeacon@1.0.0 No repository field.

**Comment by slowkoni** [comment]
Error seen on my Linux system from up script, probably due to mongodb already running on the host

ERROR: for mongo  Cannot start service mongo: driver failed programming external connectivity on endpoint beacon_mongo_1 (cf7c1df21c307763911d6de1ea0fe4773f3d058cd0395f473bcad64abc139fcd): Error starting userland proxy: listen tcp 0.0.0.0:27017: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by slowkoni** [comment]
Seems like npm succeeds with a some warnings on Linux docker, and npm start seems to work (also with warnings), and then the next steps go through and it says 

 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 824-320-907

which looks like Flask starting in its built-in server mode but on port 80 rather than 5000. But on my system, hitting port 80 at this point with a browser does not bring up what we want. 

One detail, I happened to have Flask in debug mode already running on port 5000 for a totally different thing on the host directly, not in a docker container. When I tried port 5000 thinking the beacon might actually be there, I got my own shit that I forgot about. I guess I need to get back to that project, totally forgot I was working on that one...

**Comment by trentmswanson** [comment]
I made some changes to configuration.  I added this step `source dev-settings.sh` to the readme but looks like I missed it in the hub project. This is temporary step and will eventually be replace with gulp.

**Comment by trentmswanson** [comment]
I have some updates to the dev environment I'm testing there that will further simplify things.

**Comment by trentmswanson** [comment]
Please read new development setup instructions for beacon.  I would recommend spinning down the environment and bring it back up again.  Use `bash down.sh` to spin down the environment and then `bash up.sh` to bring it back up.  Once the environment is up, it's simply `npm run setup` and then `npm start` to run the application.  The readme has been updated and I'm working on some more improvements to the dev setup.

**Comment by kilodalton** [comment]
@trentmswanson Should the pre-existing docker images from prior attempts be cleared first? e.g. `docker rmi`

**Comment by trentmswanson** [comment]
`bash down.sh` should clean things up, if you find any images sticking around it might be a good idea to remove them. When bringing up the environment again, the images should get updated. Let me know and I have the down.sh script check for additional cleanup.
